
version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravelapp
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_NAME: Laravel
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
